stages:
- name: build-image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: php-css:${CICD_EXECUTION_SEQUENCE}
      registry: 127.0.0.1:34883
- name: Deploy YAML
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
